# 系统配置
data:
  input_dir: "./data/documents"
  processed_dir: "./data/processed"
  index_path: "./data/indices/multimodal.index"

server:
  host: "0.0.0.0"
  port: 8000
  workers: 2

web:
  host: "0.0.0.0"
  port: 8501
  theme: "light"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/app.log"